# Flyway Database Configuration

flyway.url=jdbc:postgresql://localhost:5432/securecommerce_db
flyway.user=postgres
flyway.password=Pradip@123

# Migration scripts location
flyway.locations=filesystem:D:/Personal Projects/db/flyway/sql

# Schema
flyway.schemas=public

# Table used by Flyway to track migrations
flyway.table=flyway_schema_history

# Baseline for existing database
flyway.baselineOnMigrate=true

# Validate migrations before running
flyway.validateOnMigrate=true

# Encoding
flyway.encoding=UTF-8